
services:
  dotnet-app:
    build:
      context: ./customer-success-platformServer/
      dockerfile: Dockerfile
    image: sunny2883/cspfinal-dotnet-app:latest
    ports:
      - "9500:8080"
    expose:
      - 8080
    restart: always
    environment:
       POSTGRES_HOST: ${POSTGRES_HOST}
       POSTGRES_PORT: ${POSTGRES_PORT}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    depends_on:
      - postgres

  angular-app:
    build:
      context: ./CustomerSuccessPlatformClient/
      dockerfile: Dockerfile
    image: sunny2883/cspfinal-angular-app:latest
    ports:
      - "9501:4200"
    depends_on:
      - dotnet-app
    restart: always
    command: ["ng", "serve", "--host", "0.0.0.0"]


  postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
